karanS08/ctf-tools

- CONTRIBUTERS.md
- Tool.md
> New tool for Reversing

- CONTRIBUTERS.md
- Tools.md
> Add GDB Tool

- CONTRIBUTERS.md
- Tools.md
> Update tools and contributers

- CONTRIBUTERS.md
- Tool.md
Added CyberChef and resolved merge conflicts. (As I already did in my previous PR. ;) )
> Resolve merge conflicts

- CONTRIBUTERS.md
- Tools.md
> Add Spiderfoot tool

- CONTRIBUTERS.md
- Tools.md
Exiftool is an amazing tool for getting some juicy information related to images. Hope this helps.
> New tool exiftool added

- Tools.md
This PR also Closes #42
Also i made the tables a bit nicer :)
> Fully fix the whole tables and add cutter, pwntools and one_gadget

- CONTRIBUTORS.md
- Tools.md
Added my name and link of my profile.
> Updated CONTRIBUTORS.md file

- CONTRIBUTORS.md
- README.md
- Tools.md
Added payloadAllthings as a tool, added name to contributors and fixed a few grammars in README
> Added PayloadAllthing Github Repository to misc category

- CONTRIBUTORS.md
- Tools.md
Added commix (web exploitation tool)
Added PeePDF tool for forensics.
> Added Commix and PeePDF

- CONTRIBUTORS.md
- Tools.md
> add name to Contributors.md as you mention

- CONTRIBUTORS.md
- Tools.md
Added OWASP-ZAP to web-tool and name and github link to contributer file
> added OWASP-ZAP to web-tool

- CONTRIBUTORS.md
- Tools.md
Hello my name is listed in contributors and i have pr for ghidra again
> Name in Contributors MD and added ghidra 

- CONTRIBUTORS.md
- Tools.md
Hope there are no conflicts in this pr :)
> Added crypto tool for hash

- CONTRIBUTORS.md
- Tools.md
hi @karanS08 , i just updated Tools.md and CONTRIBUTORS.md. please check it out, thanks!
> Added WinHex reverse engineering

- CONTRIBUTORS.md
- Tools.md
Hey i added my name in CONTRIBUTORS.md file 
And also added two tools in the OSINT Category of Tools.md file which are:
1. Sherlock
2. Hunter.io
> Update Tools.md File And Contributors.md file

- CONTRIBUTORS.md
- Tools.md
> Fix invalid table form from `Tools.md`

- CONTRIBUTORS.md
- Tools.md
Hello @karanS08 
Thanks for this amazing tool list. I have added some tools to the list. I hope they qualify.
I have a lot more tools, they are just not organized - I wasn't sure in which category they would fit. I will try to contribute more as I organize them and if having additional categories is okay.
This year I am trying to add value to amazing lists, cheatsheets, and tools that I use that make my life as a developer easy as a part of Hacktoberfest 2022. 
Let me know if there are any issues. Appreciate the work.
> Added several tools to the list

- CONTRIBUTORS.md
- Tools.md
Hello! Added one of the most useful Ciphers tools websites I found while I worked on CTFs. Thanks!
> Add Ciphers tools website to Tools.md

- CONTRIBUTORS.md
- Tools.md
Added Hash Analyzer, Audacity under the Misc category.
> Update misc tools

- CONTRIBUTORS.md
- Tools.md
I have added the Crypto tool and my name as a contributor.
> Updated Tools.md and Contributors.md

- CONTRIBUTORS.md
- Tools.md
Added binary ninja in reverse engineering category and updated contributors.md
> Added binary ninja in revers engineering category and updated contributors.md

- CONTRIBUTORS.md
- Tools.md
Thanks for providing all the tools in one place.
> Added Cookie editor tool and updated the contributor.

- CONTRIBUTORS.md
- Tools.md
If there is something wrong with my process, please let me know, I will fix it.
> Added git scanner for sensitive information

- CONTRIBUTORS.md
- Tools.md
> [Feature] add dehashed

- CONTRIBUTORS.md
- Tools.md
I added the following CTF Tools i.e
- [Raccoon](https://github.com/evyatarmeged/Raccoon)
- [Creddump](https://github.com/moyix/creddump)
- [Network Miner](http://www.netresec.com/?page=NetworkMiner)
> Added CTF tools Raccon, Creddump and NetworkMiner

- CONTRIBUTORS.md
- README.md
Also fixed some grammar issues.
> Issue #167 - More detail to adding name to contributors steps

- CONTRIBUTORS.md
- Tools.md
**[ffuf](https://github.com/ffuf/ffuf)** added in Tools.md under Web category
> ffuf added under web category

- CONTRIBUTORS.md
- Tools.md
> Added Aircrack-ng.

- CONTRIBUTORS.md
- Tools.md
> Added a tool and updated contributors

- CONTRIBUTORS.md
- Tools.md
> Added tools for bruteforcing in ctf

- CONTRIBUTORS.md
- README.md
* Readme Updated for syncing the local repository with the github repository.
* Helps the new comers about syncing repository.
* Prevent new comers form having any issue contributing.
regards Aniket 😄
> Readme Updated

- CONTRIBUTORS.md
- Tools.md
Added tools in Brute Forcing category and updated contributors.md
> Added Brute Forcing tools to tools.md and updated contributors.md

- CONTRIBUTORS.md
- Tools.md
Added XSS Hunter to Web Tool
crt.sh to OSINT
A-Packets to Forensics.
I have also corrected some spacing.
If there is any mistake then allow me to correct it.
Thanks
> few online tools added in web tool, OSINT & Forensics category

- CONTRIBUTORS.md
- Tools.md
Added Tools: Arjun and gf in web,  and My name in contributors
> Added Tools

- CONTRIBUTORS.md
- Tools.md
Add fREdom binary exploitation tool to the list
> Add binary exploitation tool
